# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import podcast.episode_upload


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_file',
            field=models.FileField(storage=podcast.episode_upload.S3StorageWrapper(), upload_to=''),
        ),
    ]
