# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20171207_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='file_location',
        ),
    ]
